### ISSUE TITLE
Kirby: undefined function session_create_id()

### ISSUE THREAD

**Issue by distantnative** [getkirby/kirby#110]
https://sentry.io/kirby/getkirby-kirby/issues/395317387/

```
ErrorException: Uncaught Error: Call to undefined function session_create_id() in kirby/api/routes/session/create.php:34
Stack trace:
#0 [internal function]: Kirby\Cms\Api->{closure}()
#1 kirby/src/Cms/Api.php(103): Closure->call(Object(Kirby\Cms\Api))
#2 kirby/src/Cms/Api.php(126): Kirby\Cms\Api->call('session', Object(Kirby\Http\Request\Method))
#3 kirby/config/routes.php(41): Kirby\Cms\Api->result()
#4 [internal function]: Kirby\Http\Router\Result->{closure}('session')
#5 kirby/vendor/getkirby/toolkit/src/Toolkit/DI/Dependencies.php(222): Closure->call(Object(Kirby\Http\Router\Result), 'session')
#6 kirby/vendor/getkirby/http/src/Http/Router.php(143): Kirby\Toolkit\DI\Dependencies->call(Object(Closure), Array, Object(Kirby\Http\Router\Result))
#7 /kirby/src/Cms/
  File "kirby/api/routes/session/create.php", line 34, in handleFatalError
    'token' => session_create_id()
  File "kirby/vendor/sentry/sentry/lib/Raven/ErrorHandler.php", line 0
    Raven_ErrorHandler->handleFatalError
```

**Comment by bastianallgeier** [comment]
Fixed this by using simpler session tokens for now.
